services:
  okvtwo:
    build: .
    shm_size: 2.6gb
    ports:
      - "80:80"
  relay:
    container_name: webhookrelay
    image: webhookrelay/webhookrelayd:latest
    network_mode: host      
    command:
      - --mode 
      - tunnel
    restart: always
    environment:
      # Authentication
      - RELAY_KEY=ce10e352-5cf9-4c4d-b0b7-a9834f7b74b1
      - RELAY_SECRET=k74jiYF1Kzo2
      # One or more tunnels must be set in the .env file
      - TUNNELS=www
      - REGION=us-west # eu, au, us-west (defaults to eu)  
